/*除手机,邮件做非空和格式校验,公司网址不做校验外,其余都做非空校验*/
function submitForm(){
    if($('#link_man').val().trim()===""){
        $.messager.alert('提示','联系人不能为空!',"info");
        return;
    }
    if($('#link_tel').val().trim()===""){
        $.messager.alert('提示','联系人手机不能为空!',"info");
        return;
    }
    if($('#link_email').val().trim()===""){
        $.messager.alert('提示','联系人邮箱不能为空!',"info");
        return;
    }
    if($('#comp_name').val().trim()===""){
        $.messager.alert('提示','公司名称不能为空!',"info");
        return;
    }
    if($('#comp_shortname').val().trim()===""){
        $.messager.alert('提示','公司简称不能为空!',"info");
        return;
    }
    if($('#comp_addr').val().trim()===""){
        $.messager.alert('提示','公司地址不能为空!',"info");
        return;
    }
    if($('#comp_intro').val().trim()===""){
        $.messager.alert('提示','公司简介不能为空!',"info");
        return;
    }
    if($('#regist_money').val().trim()===""){
        $.messager.alert('提示','公司注册资金不能为空!',"info");
        return;
    }
    if($('#comp_boss').val().trim()===""){
        $.messager.alert('提示','公司法人不能为空!',"info");
        return;
    }
    if($('#comp_date').val().trim()===""){
        $.messager.alert('提示','公司成立时间不能为空!',"info");
        return;
    }
    if($('#phone').val().trim()===""){
        $.messager.alert('提示','公司电话不能为空!',"info");
        return;
    }
    if($('#comp_email').val().trim()===""){
        $.messager.alert('提示','公司邮件不能为空!',"info");
        return;
    }
    if($('*[name="supplier.typeid"]').val().trim()==="-"){
        $.messager.alert('提示','公司性质不能为空!',"info");
        return;
    }
    if($('*[name="supplier.empnums"]').val().trim()==="-"){
        $.messager.alert('提示','公司雇员人数不能为空!',"info");
        return;
    }
    if($('#business_scope').val().trim()===""){
        $.messager.alert('提示','公司经营范围不能为空!',"info");
        return;
    }
    if($('#business_license').val().trim()===""){
        $.messager.alert('提示','营业执照注册号不能为空!',"info");
        return;
    }
    if($('#business_license_date').val().trim()===""){
        $.messager.alert('提示','营业执照有效期不能为空!',"info");
        return;
    }
    if($('#tax_reg').val().trim()===""){
        $.messager.alert('提示','税务登记证号不能为空!',"info");
        return;
    }
    if($('#tax_reg_date').val().trim()===""){
        $.messager.alert('提示','税务登记证有效期不能为空!',"info");
        return;
    }
    if($('#organization').val().trim()===""){
        $.messager.alert('提示','组织机构代码不能为空!',"info");
        return;
    }
    if($('#organization_date').val().trim()===""){
        $.messager.alert('提示','组织机构代码有效期不能为空!',"info");
        return;
    }
    /*上传文件的校验*/
    if($('#file_business_license_file').val()==null){
        $.messager.alert('提示','营业执照附件未上传!',"info");
        return;
    }
    if($('#file_tax_reg_file').val()==null){
        $.messager.alert('提示','税务登记证附件未上传!',"info");
        return;
    }
    if($('#file_organization_file').val()==null){
        $.messager.alert('提示','组织机构代码证附件未上传!',"info");
        return;
    }
    /*----------------邮箱校验--------------------*/
    var reg_email=/^([a-z]|[0-9])+@([a-z]|[0-9])+\.+([a-z]|[0-9])+$/i;
    if(!reg_email.test($('#link_email').val().trim())){
         $.messager.alert('提示','邮箱格式不正确!正确格式为*****@****.****;例如:123@qq.com',"info");
         return;
    }
    if(!reg_email.test($('#comp_email').val().trim())){
         $.messager.alert('提示','邮箱格式不正确!正确格式为*****@****.****;例如:123@qq.com',"info");
         return;
    }
    /*---------------手机号码校验---------------*/
    var phone = $('#link_tel').val().trim();
    var reg_phone =/^1+([3-5]|[7-8])+\d{9}$/;
    if(phone.length!==11){
        $.messager.alert('提示','手机号码长度错误!请检查后重试!',"info");
        return;
    }
    if(!reg_phone.test(phone)){
        $.messager.alert('提示','手机号码格式错误!请检查后重试!',"info");
        return;
    }
     $('#dForm').ajaxSubmit(function(info){
        $.messager.alert("提示",eval("("+info+")").retMessage,"info",function () {
            window.location.href="http://localhost:8090/website/reg.jsp";
        });
    });
/*    $.ajax({
        url:'',
        data:jsonData,
        dataType:'json',
        type:'post',
        success:function(info){
            $.messager.alert("提示",info.message,"info");
        }
    });*/
}
function resetForm() {
    window.location.href="http://localhost:8090/website/reg.jsp";
}
